import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';
import ConvexClientProvider from '@/app/ConvexClientProvider';
import SessionWrapper from '@/app/SessionWrapper';
import Header from '@/app/components/Header';
import { Toaster } from '@/components/ui/toaster';

const lato = Lato({ weight: ['300', '400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  icons: {
    icon: './icon.svg',
  },
  title: 'Team file management',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={`${lato.className}`}>
          <ConvexClientProvider>
            <Header />
            {children}
          </ConvexClientProvider>
          <Toaster />
        </body>
      </html>
    </SessionWrapper>
  );
}
