import type { Metadata } from 'next';
import './globals.css';
import ConvexClientProvider from '@/app/ConvexClientProvider';
import SessionWrapper from '@/app/SessionWrapper';
import Header from '@/app/components/Header';
import { Toaster } from '@/components/ui/toaster';
import { asap, lato } from '@/app/fonts';
import BuyMeACoffee from '@/app/components/common/BuyMeACoffee';

export const metadata: Metadata = {
  icons: {
    icon: './icon.svg',
  },
  title: 'Team file management',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={`${lato.variable} ${asap.variable} font-inter cursor-default`}>
          <ConvexClientProvider>
            <Header />
            {children}
          </ConvexClientProvider>
          <BuyMeACoffee />
          <Toaster />
        </body>
      </html>
    </SessionWrapper>
  );
}
